// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/templates" | "/admin/templates/[id]/edit" | "/admin/templates/new" | "/admin/users" | "/login" | "/my-pages" | "/my-pages/[id]" | "/preview/[id]" | "/register" | "/templates" | "/templates/[id]/customize"
type AppRouteHandlerRoutes = "/api/customizations" | "/api/customizations/[id]" | "/api/customizations/[id]/publish" | "/api/templates" | "/api/templates/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/templates": {}
  "/admin/templates/[id]/edit": { "id": string; }
  "/admin/templates/new": {}
  "/admin/users": {}
  "/api/customizations": {}
  "/api/customizations/[id]": { "id": string; }
  "/api/customizations/[id]/publish": { "id": string; }
  "/api/templates": {}
  "/api/templates/[id]": { "id": string; }
  "/login": {}
  "/my-pages": {}
  "/my-pages/[id]": { "id": string; }
  "/preview/[id]": { "id": string; }
  "/register": {}
  "/templates": {}
  "/templates/[id]/customize": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
